version: '3.8'

services:
  web:
    build: .
    container_name: php_container
    environment:
      DB_HOST: db
    volumes:
      - ./app:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_DATABASE: "escritor_emprestimo"
      MYSQL_USER: "escritor_emprestimo"
      MYSQL_PASSWORD: "Hl)O=qKRv4Sl"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
